source 'https://rubygems.org'

gem 'berkshelf', '~> 4.3.0'
gem 'chef', '= 12.10.24'
gem 'test-kitchen'
gem 'kitchen-openstack'
gem 'kitchen-vagrant'
gem 'rubocop'
gem 'foodcritic', '~> 6.3.0'
gem 'busser'
gem 'chefspec'
gem 'rspec'
gem 'rake'
