name             'nodejs-webapp'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'apache2'
description      'Installs/Configures nodejs-webapp'
long_description 'Installs/Configures nodejs-webapp'
version          '1.0.0'

depends 'build-essential'
depends 'git'
depends 'magic_shell'
depends 'nodejs'
depends 'pm2'
